name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: '[17.0,18.0)'

      - name: Build (Release | Any CPU)
        shell: cmd
        run: scripts\build.cmd

      - name: Collect artifact (HttpStatus.exe only)
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path dist | Out-Null
          Copy-Item -Path "HttpStatus\bin\Release\HttpStatus.exe" -Destination dist -Force

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: HttpStatus-${{ github.ref_name }}
          path: dist/HttpStatus.exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/HttpStatus.exe
          draft: false
          prerelease: false
          # body_path: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
